import { ActionTypes } from '@mui/base';
import React from 'react'
import { connect } from 'react-redux';
import * as actionsTypes from '../../../store/actions/actionsTypes';

function Store(props: any) {

    const handleScroll = (e: any) => {
        let storeDiv = document.getElementById('store_info')
        props.handleScroll(storeDiv?.scrollTop);
    };


    return (
        <div id='store_info' style={{ "height": "70vh", "overflow": "scroll", "marginTop": "90px" }} onScroll={handleScroll}>
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Pageyou are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page
            you are in Store Page

        </div>
    );
}


const mapStateToProps = (state: any) => {
    return {
        store: state.store
    }
};

const mapDispatchToProps = (dispatch: any) => {
    return {
        handleScroll: (scrollY: number) => dispatch({ type: actionsTypes.SCROLL, scrollY: scrollY })
    }
};

export default connect(mapStateToProps, mapDispatchToProps)(Store);