export const LOADCONFIG = 'LOADCONFIG';

export const SCROLL = 'SCROLL';

export const GETSTORES = 'GETSTORES';
export const SAVESTORESLOCALLY = 'SAVESTORESLOCALLY';
export const UNMOUNTSTORESLISTS = 'UNMOUNTSTORESLISTS';
export const GETSTOREERR = 'GETSTOREERR';

export const GETSTOREGATEGORIES = 'GETSTOREGATEGORIES';
export const SAVESTORECATEGORIESLOCALLY = 'SAVESTORECATEGORIESLOCALLY';

export const SETSELECTEDSTORE = 'SETSELECTEDSTORE';
export const SETSELECTEDITEM = 'SETSELECTEDITEM';

export const GETITEMIOPTIONS = 'GETITEMIOPTIONS';
export const SAVEOPTIONSLOCALLY = 'SAVEOPTIONSLOCALLY';

export const GETITEMEXTRAS = 'GETITEMEXTRAS';
export const GETVARIANTEXTRAS = 'GETVARIANTEXTRAS';